### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by asulwer** [npodbielski/XamarinSamples#1]
getting a compile error.  I altered the namespace to reflect being added to my project.

![untitled](https://cloud.githubusercontent.com/assets/7673412/19819885/4c8f35de-9d1c-11e6-9380-250f3767d7e4.png)

**Comment by asulwer** [comment]
to fix you need to add ContentPage

public partial class MasterDetailControl : ContentPage

**Comment by npodbielski** [comment]
Generally if you have correctly configured project you do not need to add base type to xaml page in code. Adding it in XAML is enough.
